/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TentangKamiRouteImport } from './routes/tentang-kami'
import { Route as SyaratDanKetentuanRouteImport } from './routes/syarat-dan-ketentuan'
import { Route as LacakPesananRouteImport } from './routes/lacak-pesanan'
import { Route as KetentuanGaransiRouteImport } from './routes/ketentuan-garansi'
import { Route as KebijakanPrivasiRouteImport } from './routes/kebijakan-privasi'
import { Route as HubungiKamiRouteImport } from './routes/hubungi-kami'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsProductidRouteImport } from './routes/products/$productid'
import { Route as ProductsProductSlugRouteImport } from './routes/products/$productSlug'
import { Route as CollectionsCategoryRouteImport } from './routes/collections/$category'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout/success'
import { Route as CheckoutCancelRouteImport } from './routes/checkout/cancel'

const TentangKamiRoute = TentangKamiRouteImport.update({
  id: '/tentang-kami',
  path: '/tentang-kami',
  getParentRoute: () => rootRouteImport,
} as any)
const SyaratDanKetentuanRoute = SyaratDanKetentuanRouteImport.update({
  id: '/syarat-dan-ketentuan',
  path: '/syarat-dan-ketentuan',
  getParentRoute: () => rootRouteImport,
} as any)
const LacakPesananRoute = LacakPesananRouteImport.update({
  id: '/lacak-pesanan',
  path: '/lacak-pesanan',
  getParentRoute: () => rootRouteImport,
} as any)
const KetentuanGaransiRoute = KetentuanGaransiRouteImport.update({
  id: '/ketentuan-garansi',
  path: '/ketentuan-garansi',
  getParentRoute: () => rootRouteImport,
} as any)
const KebijakanPrivasiRoute = KebijakanPrivasiRouteImport.update({
  id: '/kebijakan-privasi',
  path: '/kebijakan-privasi',
  getParentRoute: () => rootRouteImport,
} as any)
const HubungiKamiRoute = HubungiKamiRouteImport.update({
  id: '/hubungi-kami',
  path: '/hubungi-kami',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductidRoute = ProductsProductidRouteImport.update({
  id: '/products/$productid',
  path: '/products/$productid',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductSlugRoute = ProductsProductSlugRouteImport.update({
  id: '/products/$productSlug',
  path: '/products/$productSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsCategoryRoute = CollectionsCategoryRouteImport.update({
  id: '/collections/$category',
  path: '/collections/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutCancelRoute = CheckoutCancelRouteImport.update({
  id: '/checkout/cancel',
  path: '/checkout/cancel',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hubungi-kami': typeof HubungiKamiRoute
  '/kebijakan-privasi': typeof KebijakanPrivasiRoute
  '/ketentuan-garansi': typeof KetentuanGaransiRoute
  '/lacak-pesanan': typeof LacakPesananRoute
  '/syarat-dan-ketentuan': typeof SyaratDanKetentuanRoute
  '/tentang-kami': typeof TentangKamiRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/collections/$category': typeof CollectionsCategoryRoute
  '/products/$productSlug': typeof ProductsProductSlugRoute
  '/products/$productid': typeof ProductsProductidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hubungi-kami': typeof HubungiKamiRoute
  '/kebijakan-privasi': typeof KebijakanPrivasiRoute
  '/ketentuan-garansi': typeof KetentuanGaransiRoute
  '/lacak-pesanan': typeof LacakPesananRoute
  '/syarat-dan-ketentuan': typeof SyaratDanKetentuanRoute
  '/tentang-kami': typeof TentangKamiRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/collections/$category': typeof CollectionsCategoryRoute
  '/products/$productSlug': typeof ProductsProductSlugRoute
  '/products/$productid': typeof ProductsProductidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hubungi-kami': typeof HubungiKamiRoute
  '/kebijakan-privasi': typeof KebijakanPrivasiRoute
  '/ketentuan-garansi': typeof KetentuanGaransiRoute
  '/lacak-pesanan': typeof LacakPesananRoute
  '/syarat-dan-ketentuan': typeof SyaratDanKetentuanRoute
  '/tentang-kami': typeof TentangKamiRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/collections/$category': typeof CollectionsCategoryRoute
  '/products/$productSlug': typeof ProductsProductSlugRoute
  '/products/$productid': typeof ProductsProductidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hubungi-kami'
    | '/kebijakan-privasi'
    | '/ketentuan-garansi'
    | '/lacak-pesanan'
    | '/syarat-dan-ketentuan'
    | '/tentang-kami'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/collections/$category'
    | '/products/$productSlug'
    | '/products/$productid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hubungi-kami'
    | '/kebijakan-privasi'
    | '/ketentuan-garansi'
    | '/lacak-pesanan'
    | '/syarat-dan-ketentuan'
    | '/tentang-kami'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/collections/$category'
    | '/products/$productSlug'
    | '/products/$productid'
  id:
    | '__root__'
    | '/'
    | '/hubungi-kami'
    | '/kebijakan-privasi'
    | '/ketentuan-garansi'
    | '/lacak-pesanan'
    | '/syarat-dan-ketentuan'
    | '/tentang-kami'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/collections/$category'
    | '/products/$productSlug'
    | '/products/$productid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HubungiKamiRoute: typeof HubungiKamiRoute
  KebijakanPrivasiRoute: typeof KebijakanPrivasiRoute
  KetentuanGaransiRoute: typeof KetentuanGaransiRoute
  LacakPesananRoute: typeof LacakPesananRoute
  SyaratDanKetentuanRoute: typeof SyaratDanKetentuanRoute
  TentangKamiRoute: typeof TentangKamiRoute
  CheckoutCancelRoute: typeof CheckoutCancelRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  CollectionsCategoryRoute: typeof CollectionsCategoryRoute
  ProductsProductSlugRoute: typeof ProductsProductSlugRoute
  ProductsProductidRoute: typeof ProductsProductidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tentang-kami': {
      id: '/tentang-kami'
      path: '/tentang-kami'
      fullPath: '/tentang-kami'
      preLoaderRoute: typeof TentangKamiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/syarat-dan-ketentuan': {
      id: '/syarat-dan-ketentuan'
      path: '/syarat-dan-ketentuan'
      fullPath: '/syarat-dan-ketentuan'
      preLoaderRoute: typeof SyaratDanKetentuanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lacak-pesanan': {
      id: '/lacak-pesanan'
      path: '/lacak-pesanan'
      fullPath: '/lacak-pesanan'
      preLoaderRoute: typeof LacakPesananRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ketentuan-garansi': {
      id: '/ketentuan-garansi'
      path: '/ketentuan-garansi'
      fullPath: '/ketentuan-garansi'
      preLoaderRoute: typeof KetentuanGaransiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kebijakan-privasi': {
      id: '/kebijakan-privasi'
      path: '/kebijakan-privasi'
      fullPath: '/kebijakan-privasi'
      preLoaderRoute: typeof KebijakanPrivasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hubungi-kami': {
      id: '/hubungi-kami'
      path: '/hubungi-kami'
      fullPath: '/hubungi-kami'
      preLoaderRoute: typeof HubungiKamiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productid': {
      id: '/products/$productid'
      path: '/products/$productid'
      fullPath: '/products/$productid'
      preLoaderRoute: typeof ProductsProductidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productSlug': {
      id: '/products/$productSlug'
      path: '/products/$productSlug'
      fullPath: '/products/$productSlug'
      preLoaderRoute: typeof ProductsProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$category': {
      id: '/collections/$category'
      path: '/collections/$category'
      fullPath: '/collections/$category'
      preLoaderRoute: typeof CollectionsCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/cancel': {
      id: '/checkout/cancel'
      path: '/checkout/cancel'
      fullPath: '/checkout/cancel'
      preLoaderRoute: typeof CheckoutCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HubungiKamiRoute: HubungiKamiRoute,
  KebijakanPrivasiRoute: KebijakanPrivasiRoute,
  KetentuanGaransiRoute: KetentuanGaransiRoute,
  LacakPesananRoute: LacakPesananRoute,
  SyaratDanKetentuanRoute: SyaratDanKetentuanRoute,
  TentangKamiRoute: TentangKamiRoute,
  CheckoutCancelRoute: CheckoutCancelRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  CollectionsCategoryRoute: CollectionsCategoryRoute,
  ProductsProductSlugRoute: ProductsProductSlugRoute,
  ProductsProductidRoute: ProductsProductidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
