/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsProductidRouteImport } from './routes/products/$productid'
import { Route as ProductsProductSlugRouteImport } from './routes/products/$productSlug'
import { Route as CollectionsCategoryRouteImport } from './routes/collections/$category'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout/success'
import { Route as CheckoutCancelRouteImport } from './routes/checkout/cancel'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductidRoute = ProductsProductidRouteImport.update({
  id: '/products/$productid',
  path: '/products/$productid',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductSlugRoute = ProductsProductSlugRouteImport.update({
  id: '/products/$productSlug',
  path: '/products/$productSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsCategoryRoute = CollectionsCategoryRouteImport.update({
  id: '/collections/$category',
  path: '/collections/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutCancelRoute = CheckoutCancelRouteImport.update({
  id: '/checkout/cancel',
  path: '/checkout/cancel',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/collections/$category': typeof CollectionsCategoryRoute
  '/products/$productSlug': typeof ProductsProductSlugRoute
  '/products/$productid': typeof ProductsProductidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/collections/$category': typeof CollectionsCategoryRoute
  '/products/$productSlug': typeof ProductsProductSlugRoute
  '/products/$productid': typeof ProductsProductidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/collections/$category': typeof CollectionsCategoryRoute
  '/products/$productSlug': typeof ProductsProductSlugRoute
  '/products/$productid': typeof ProductsProductidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/collections/$category'
    | '/products/$productSlug'
    | '/products/$productid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/collections/$category'
    | '/products/$productSlug'
    | '/products/$productid'
  id:
    | '__root__'
    | '/'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/collections/$category'
    | '/products/$productSlug'
    | '/products/$productid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutCancelRoute: typeof CheckoutCancelRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  CollectionsCategoryRoute: typeof CollectionsCategoryRoute
  ProductsProductSlugRoute: typeof ProductsProductSlugRoute
  ProductsProductidRoute: typeof ProductsProductidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productid': {
      id: '/products/$productid'
      path: '/products/$productid'
      fullPath: '/products/$productid'
      preLoaderRoute: typeof ProductsProductidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productSlug': {
      id: '/products/$productSlug'
      path: '/products/$productSlug'
      fullPath: '/products/$productSlug'
      preLoaderRoute: typeof ProductsProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$category': {
      id: '/collections/$category'
      path: '/collections/$category'
      fullPath: '/collections/$category'
      preLoaderRoute: typeof CollectionsCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/cancel': {
      id: '/checkout/cancel'
      path: '/checkout/cancel'
      fullPath: '/checkout/cancel'
      preLoaderRoute: typeof CheckoutCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutCancelRoute: CheckoutCancelRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  CollectionsCategoryRoute: CollectionsCategoryRoute,
  ProductsProductSlugRoute: ProductsProductSlugRoute,
  ProductsProductidRoute: ProductsProductidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
